# Generated by Django 5.0.6 on 2024-06-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('phone_number', models.IntegerField()),
                ('adhaar_number', models.IntegerField()),
                ('MIDICAL_LICENCE_NO', models.TextField()),
                ('specialization', models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Neurologist', 'Neurologist'), ('Pediatrician', 'Pediatrician'), ('Psychiatrist', 'Psychiatrist'), ('Radiologist', 'Radiologist'), ('Surgeon', 'Surgeon'), ('Orthopedic', 'Orthopedic'), ('Ophthalmologist', 'Ophthalmologist'), ('Gynecologist', 'Gynecologist'), ('Oncologist', 'Oncologist'), ('Anesthesiologist', 'Anesthesiologist'), ('Endocrinologist', 'Endocrinologist'), ('Gastroenterologist', 'Gastroenterologist'), ('Nephrologist', 'Nephrologist'), ('Rheumatologist', 'Rheumatologist'), ('Pulmonologist', 'Pulmonologist'), ('Urologist', 'Urologist'), ('Pathologist', 'Pathologist'), ('ENT Specialist', 'ENT Specialist')], max_length=50)),
                ('food_type', models.CharField(choices=[('Veg', 'Veg'), ('Non_Veg', 'Non_Veg')], max_length=15)),
                ('years_of_experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('phone_number', models.IntegerField()),
                ('current_medications', models.TextField()),
                ('ALLERGIES', models.TextField()),
                ('past_medical_condition', models.TextField()),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('recent_test_details', models.FileField(upload_to='user_details/')),
                ('food_type', models.CharField(choices=[('Veg', 'Veg'), ('Non_Veg', 'Non_Veg')], max_length=15)),
                ('address', models.TextField()),
            ],
        ),
    ]
