# Generated by Django 5.0.6 on 2024-06-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetails',
            name='adhaar_number',
            field=models.BigIntegerField(),
        ),
    ]
