# Generated by Django 5.0.6 on 2024-06-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthify', '0002_alter_doctordetails_adhaar_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='userRequestForDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('specialization', models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Neurologist', 'Neurologist'), ('Pediatrician', 'Pediatrician'), ('Psychiatrist', 'Psychiatrist'), ('Radiologist', 'Radiologist'), ('Surgeon', 'Surgeon'), ('Orthopedic', 'Orthopedic'), ('Ophthalmologist', 'Ophthalmologist'), ('Gynecologist', 'Gynecologist'), ('Oncologist', 'Oncologist'), ('Anesthesiologist', 'Anesthesiologist'), ('Endocrinologist', 'Endocrinologist'), ('Gastroenterologist', 'Gastroenterologist'), ('Nephrologist', 'Nephrologist'), ('Rheumatologist', 'Rheumatologist'), ('Pulmonologist', 'Pulmonologist'), ('Urologist', 'Urologist'), ('Pathologist', 'Pathologist'), ('ENT Specialist', 'ENT Specialist')], max_length=50)),
            ],
        ),
    ]
