# Generated by Django 5.0.6 on 2024-06-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthify', '0004_uploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequestfordoctor',
            name='villageName',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
    ]
