# Generated by Django 5.0.6 on 2024-06-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthify', '0005_userrequestfordoctor_villagename'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataOfRoomIDs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomID', models.CharField(max_length=100)),
            ],
        ),
    ]
