# Generated by Django 5.0.7 on 2024-07-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthify", "0006_dataofroomids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctordetails",
            name="phone_number",
            field=models.CharField(max_length=15),
        ),
    ]
