# Generated by Django 5.0.7 on 2024-07-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthify", "0007_alter_doctordetails_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="phone_number",
            field=models.CharField(max_length=15),
        ),
    ]
