# Generated by Django 5.0.7 on 2024-07-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_auto_20170803_0746"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodbankdata",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
